FROM $CI_REGISTRY_IMAGE:common-$CI_COMMIT_SHA

ENV DEBIAN_FRONTEND noninteractive

# Prepare system requirements
RUN apt-get install -y --no-install-recommends \
            python \
            python-dev

# The pip provided by python-pip is usually too old.
RUN wget -O - https://bootstrap.pypa.io/get-pip.py | python
