# This builds just the bare bones of the 'xhg2' image.  It includes only the
# basics.  You can however, use to build different deployments.  Just
# add/remove the desired code from the Pipfile[.lock] and add/remove the
# subtrees if so desired.
FROM $CI_REGISTRY_IMAGE:common-$CI_COMMIT_SHA

# Prepare system requirements
RUN apt-get install -y --no-install-recommends \
           python3 \
           python3-dev

# The pip provided by python-pip is usually too old.
RUN wget -O - https://bootstrap.pypa.io/get-pip.py | python3
