FROM $CI_REGISTRY_IMAGE:common-$CI_COMMIT_SHA

ENV DEBIAN_FRONTEND noninteractive

# Prepare system requirements
RUN apt-get install -y --no-install-recommends \
            python \
            python-pip \
            python-setuptools \
            python-dev \

# The pip provided by python-pip is usually too old.
RUN pip install -U pip
